version: 2

sources:
  - name: raw
    database: njc-ezpass
    schema: ezpass_data
    description: Raw EZ-Pass transaction data loaded from GCS by Airflow
    
    tables:
      - name: bronze
        description: Raw transactions with all STRING types from CSV files
        columns:
          - name: posting_date
            description: Date transaction was posted (STRING YYYY-MM-DD)
            
          - name: transaction_date
            description: Date of the actual transaction (STRING YYYY-MM-DD)
            
          - name: tag_plate_number
            description: EZ-Pass tag or license plate number
            
          - name: agency
            description: Toll agency (e.g., NJTA)
            
          - name: description
            description: Transaction description
            
          - name: entry_time
            description: Entry timestamp (STRING YYYY-MM-DD HH:MM:SS)
            
          - name: entry_plaza
            description: Entry toll plaza name
            
          - name: entry_lane
            description: Entry lane number
            
          - name: exit_time
            description: Exit timestamp (STRING YYYY-MM-DD HH:MM:SS)
            
          - name: exit_plaza
            description: Exit toll plaza name
            
          - name: exit_lane
            description: Exit lane number
            
          - name: vehicle_type_code
            description: Vehicle classification code
            
          - name: amount
            description: Transaction amount (STRING, negative for tolls)
            
          - name: prepaid
            description: Prepaid amount (STRING)
            
          - name: plan_rate
            description: Rate plan type
            
          - name: fare_type
            description: Fare category
            
          - name: balance
            description: Account balance after transaction (STRING)
            
          - name: loaded_at
            description: Timestamp when loaded to BigQuery (STRING)
            
          - name: source_file
            description: Original CSV filename

      - name: holidays
        description: BigQuery with list of NJ Courts Holidays from 2025 to 2035
      
      - name: address_to_miles
        description: Distance lookup table for plaza-to-plaza routes in miles