{{ config(
    materialized='ephemeral',
    tags=['silver', 'intermediate']
) }}

WITH cleaned AS (
    SELECT * FROM {{ ref('_silver__cleaning') }}
),

enriched AS (
    SELECT
        *,
        
        -- Agency name enrichment
        CASE agency
            WHEN 'GSP' THEN 'Garden State Parkway'
            WHEN 'NJTP' THEN 'New Jersey Turnpike'
            WHEN 'SJ' THEN 'South Jersey Transportation Authority'
            WHEN 'PTC' THEN 'Pennsylvania Turnpike Commission'
            WHEN 'DRJTBC' THEN 'Delaware River Joint Toll Bridge Commission'
            WHEN 'DRPA' THEN 'Delaware River Port Authority'
            WHEN 'PANYNJ' THEN 'Port Authority of NY & NJ'
            WHEN 'BCBC' THEN 'Burlington County Bridge Commission'
            WHEN 'NJ E-ZPASS' THEN 'NJ E-ZPass (back office)'
            WHEN 'CBDTP' THEN '(verify) — possible CBBT'
            ELSE NULL  -- Unknown values become NULL
        END as agency_name,

        -- Entry plaza name enrichment
        CASE entry_plaza
            -- GSP (Garden State Parkway)
            WHEN 'PVK' THEN 'Pascack Valley'
            WHEN 'PRS' THEN 'Paramus South'
            WHEN 'PRN' THEN 'Paramus North'
            WHEN 'BER' THEN 'Bergen'
            WHEN 'SAB' THEN 'Saddle Brook'
            WHEN 'CLS' THEN 'Clifton South'
            WHEN 'CLN' THEN 'Clifton North'
            WHEN 'PSS' THEN 'Passaic South'
            WHEN 'PSN' THEN 'Passaic North'
            WHEN 'WAS' THEN 'Watchung South'
            WHEN 'WAN' THEN 'Watchung North'
            WHEN 'ESS' THEN 'Essex'
            WHEN 'BLS' THEN 'Bloomfield South'
            WHEN 'BLN' THEN 'Bloomfield North'
            WHEN 'EOR' THEN 'East Orange'
            WHEN 'IRS' THEN 'Irvington South'
            WHEN 'IRN' THEN 'Irvington North'
            WHEN 'UNR' THEN 'Union Ramp'
            WHEN 'UNI' THEN 'Union'
            WHEN 'RAS' THEN 'Raritan South'
            WHEN 'MAT' THEN 'Matawan'
            WHEN 'KEY' THEN 'Keyport'
            WHEN 'HOS' THEN 'Holmdel South'
            WHEN 'HON' THEN 'Holmdel North'
            WHEN 'RBS' THEN 'Red Bank South'
            WHEN 'RBN' THEN 'Red Bank North'
            WHEN 'EAT' THEN 'Eatontown'
            WHEN 'ASP' THEN 'Asbury Park'
            WHEN 'BES' THEN 'Belmar South'
            WHEN 'BEN' THEN 'Belmar North'
            WHEN 'BRS' THEN 'Brick South'
            WHEN 'BRN' THEN 'Brick North'
            WHEN 'LWS' THEN 'Lakewood South'
            WHEN 'LWN' THEN 'Lakewood North'
            WHEN 'TRV' THEN 'Toms River'
            WHEN 'LRS' THEN 'Lacey Rd South'
            WHEN 'LRN' THEN 'Lacey Rd North'
            WHEN 'BAR' THEN 'Barnegat'
            WHEN 'BKS' THEN 'Berkeley Ramp South'
            WHEN 'BKN' THEN 'Berkeley Ramp North'
            WHEN 'NGR' THEN 'New Gretna'
            WHEN 'WRS' THEN 'Waretown South'
            WHEN 'WRN' THEN 'Waretown North'
            WHEN 'SPT' THEN 'Somers Point'
            WHEN 'GEG' THEN 'Great Egg'
            WHEN 'CMY' THEN 'Cape May'
            WHEN 'WWS' THEN 'Wildwood South'
            WHEN 'WWN' THEN 'Wildwood North'
            WHEN 'SAY' THEN 'Sayreville'
            -- NJTP (Turnpike)
            WHEN '1' THEN 'Delaware Memorial Bridge'
            WHEN '2' THEN 'Swedesboro/Chester'
            WHEN '3' THEN 'Woodbury/S. Camden/NJ Aquarium'
            WHEN '4' THEN 'Camden/Philadelphia/NJ Aquarium'
            WHEN '5' THEN 'Burlington/Mt. Holly'
            WHEN '6' THEN 'PA Turnpike/Florence'
            WHEN '6A' THEN 'PA Turnpike/Florence'
            WHEN '6B' THEN 'Rte. 130 Credit Ramp'
            WHEN '7' THEN 'Bordentown/Trenton'
            WHEN '7A' THEN 'I-195/Trenton/Shore Points'
            WHEN '8' THEN 'Hightstown/Freehold'
            WHEN '8A' THEN 'Jamesburg/Cranbury'
            WHEN '9' THEN 'New Brunswick/Admin Bldg'
            WHEN '10' THEN 'I-287/Metuchen/Edison Twsp'
            WHEN '11' THEN 'GSP/Woodbridge/The Amboys'
            WHEN '12' THEN 'Carteret/Rahway'
            WHEN '13' THEN 'I-278/Eliz/Goethals/Verrazano'
            WHEN '13A' THEN 'Newark Aprt/Elizabeth Seaport'
            WHEN '14' THEN 'I-78/Newark Airport'
            WHEN '14A' THEN 'Bayonne'
            WHEN '14B' THEN 'Jersey City/Liberty State Park'
            WHEN '14C' THEN 'Holland Tunnel'
            WHEN '15E' THEN 'Newark/Jersey City'
            WHEN '15W' THEN 'I-280/Newark/The Oranges'
            WHEN '15X' THEN 'Secaucus Transfer Station'
            WHEN '16E' THEN 'Lincoln Tunnel/NJ 3/Secaucus'
            WHEN '16W' THEN 'Sprtsplx/NJ 3/Secaucus/Ruthrfrd'
            WHEN '17' THEN 'Secaucus/US 46'
            WHEN '18E' THEN 'Lincoln Tunnel/NJ 3/Secaucus'
            WHEN '18W' THEN 'Geo Washington Br/US 46/I-80'
            WHEN '19W' THEN 'Carlstadt'
            -- SJ (South Jersey)
            WHEN 'APL' THEN 'Pleasantville Mainline Barrier'
            WHEN 'AR9' THEN 'Route 9'
            WHEN 'APO' THEN 'Pomona'
            WHEN 'ACY' THEN 'AC Airport'
            WHEN 'AML' THEN 'Mays Landing'
            WHEN 'A50' THEN 'Route 50'
            WHEN 'AEH' THEN 'Egg Harbor Mainline Barrier'
            WHEN 'AH' THEN 'Hammonton Ramp'
            WHEN 'AWN' THEN 'Winslow Ramp'
            WHEN 'AWL' THEN 'Williamstown Ramp'
            WHEN 'ACK' THEN 'Cross Keys'
            WHEN 'OCL' THEN 'Ocean City-Longport Bridge'
            WHEN 'CIB' THEN 'Corsons Inlet Bridge'
            WHEN 'TIB' THEN 'Townsends Inlet Bridge'
            WHEN 'GSB' THEN 'Grassy Sound Bridge'
            WHEN 'MTB' THEN 'Middle Thorofare Bridge'
            -- DRPA
            WHEN 'BRB' THEN 'Betsy Ross Br'
            WHEN 'BFB' THEN 'Ben Franklin Br'
            WHEN 'WWB' THEN 'Walt Whitman Br'
            WHEN 'CBB' THEN 'Commodore Barry Br'
            -- DRBA
            WHEN 'DMB' THEN 'Delaware Memorial Br'
            -- BCBC
            WHEN 'TPB' THEN 'Tacony Palmyra Br'
            WHEN 'BBB' THEN 'Burlington Bristol Br'
            -- DRJTBC
            WHEN 'T-M' THEN 'Trenton-Morrisville Br'
            WHEN 'NHL' THEN 'New Hope-Lambertville Br'
            WHEN 'I78' THEN 'I-78 Br'
            WHEN 'E-P' THEN 'Easton-Phillipsburg Br'
            WHEN 'P-C' THEN 'Portland-Columbia Br'
            WHEN 'DWG' THEN 'Delaware Water Gap Br'
            WHEN 'M-M' THEN 'Milford-Montague Br'
            WHEN 'O78' THEN 'Interstate 78-ORT'
            WHEN 'ODW' THEN 'Delaware Water Gap-ORT'
            WHEN 'OSF' THEN 'Scudder Falls Br'
            ELSE NULL  -- Unknown values become NULL
        END as entry_plaza_name,
        
        -- Exit plaza name enrichment
        CASE exit_plaza
            -- GSP
            WHEN 'PVK' THEN 'Pascack Valley'
            WHEN 'PRS' THEN 'Paramus South'
            WHEN 'PRN' THEN 'Paramus North'
            WHEN 'BER' THEN 'Bergen'
            WHEN 'SAB' THEN 'Saddle Brook'
            WHEN 'CLS' THEN 'Clifton South'
            WHEN 'CLN' THEN 'Clifton North'
            WHEN 'PSS' THEN 'Passaic South'
            WHEN 'PSN' THEN 'Passaic North'
            WHEN 'WAS' THEN 'Watchung South'
            WHEN 'WAN' THEN 'Watchung North'
            WHEN 'ESS' THEN 'Essex'
            WHEN 'BLS' THEN 'Bloomfield South'
            WHEN 'BLN' THEN 'Bloomfield North'
            WHEN 'EOR' THEN 'East Orange'
            WHEN 'IRS' THEN 'Irvington South'
            WHEN 'IRN' THEN 'Irvington North'
            WHEN 'UNR' THEN 'Union Ramp'
            WHEN 'UNI' THEN 'Union'
            WHEN 'RAS' THEN 'Raritan South'
            WHEN 'MAT' THEN 'Matawan'
            WHEN 'KEY' THEN 'Keyport'
            WHEN 'HOS' THEN 'Holmdel South'
            WHEN 'HON' THEN 'Holmdel North'
            WHEN 'RBS' THEN 'Red Bank South'
            WHEN 'RBN' THEN 'Red Bank North'
            WHEN 'EAT' THEN 'Eatontown'
            WHEN 'ASP' THEN 'Asbury Park'
            WHEN 'BES' THEN 'Belmar South'
            WHEN 'BEN' THEN 'Belmar North'
            WHEN 'BRS' THEN 'Brick South'
            WHEN 'BRN' THEN 'Brick North'
            WHEN 'LWS' THEN 'Lakewood South'
            WHEN 'LWN' THEN 'Lakewood North'
            WHEN 'TRV' THEN 'Toms River'
            WHEN 'LRS' THEN 'Lacey Rd South'
            WHEN 'LRN' THEN 'Lacey Rd North'
            WHEN 'BAR' THEN 'Barnegat'
            WHEN 'BKS' THEN 'Berkeley Ramp South'
            WHEN 'BKN' THEN 'Berkeley Ramp North'
            WHEN 'NGR' THEN 'New Gretna'
            WHEN 'WRS' THEN 'Waretown South'
            WHEN 'WRN' THEN 'Waretown North'
            WHEN 'SPT' THEN 'Somers Point'
            WHEN 'GEG' THEN 'Great Egg'
            WHEN 'CMY' THEN 'Cape May'
            WHEN 'WWS' THEN 'Wildwood South'
            WHEN 'WWN' THEN 'Wildwood North'
            WHEN 'SAY' THEN 'Sayreville'
            -- NJTP
            WHEN '1' THEN 'Delaware Memorial Bridge'
            WHEN '2' THEN 'Swedesboro/Chester'
            WHEN '3' THEN 'Woodbury/S. Camden/NJ Aquarium'
            WHEN '4' THEN 'Camden/Philadelphia/NJ Aquarium'
            WHEN '5' THEN 'Burlington/Mt. Holly'
            WHEN '6' THEN 'PA Turnpike/Florence'
            WHEN '6A' THEN 'PA Turnpike/Florence'
            WHEN '6B' THEN 'Rte. 130 Credit Ramp'
            WHEN '7' THEN 'Bordentown/Trenton'
            WHEN '7A' THEN 'I-195/Trenton/Shore Points'
            WHEN '8' THEN 'Hightstown/Freehold'
            WHEN '8A' THEN 'Jamesburg/Cranbury'
            WHEN '9' THEN 'New Brunswick/Admin Bldg'
            WHEN '10' THEN 'I-287/Metuchen/Edison Twsp'
            WHEN '11' THEN 'GSP/Woodbridge/The Amboys'
            WHEN '12' THEN 'Carteret/Rahway'
            WHEN '13' THEN 'I-278/Eliz/Goethals/Verrazano'
            WHEN '13A' THEN 'Newark Aprt/Elizabeth Seaport'
            WHEN '14' THEN 'I-78/Newark Airport'
            WHEN '14A' THEN 'Bayonne'
            WHEN '14B' THEN 'Jersey City/Liberty State Park'
            WHEN '14C' THEN 'Holland Tunnel'
            WHEN '15E' THEN 'Newark/Jersey City'
            WHEN '15W' THEN 'I-280/Newark/The Oranges'
            WHEN '15X' THEN 'Secaucus Transfer Station'
            WHEN '16E' THEN 'Lincoln Tunnel/NJ 3/Secaucus'
            WHEN '16W' THEN 'Sprtsplx/NJ 3/Secaucus/Ruthrfrd'
            WHEN '17' THEN 'Secaucus/US 46'
            WHEN '18E' THEN 'Lincoln Tunnel/NJ 3/Secaucus'
            WHEN '18W' THEN 'Geo Washington Br/US 46/I-80'
            WHEN '19W' THEN 'Carlstadt'
            -- SJ
            WHEN 'APL' THEN 'Pleasantville Mainline Barrier'
            WHEN 'AR9' THEN 'Route 9'
            WHEN 'APO' THEN 'Pomona'
            WHEN 'ACY' THEN 'AC Airport'
            WHEN 'AML' THEN 'Mays Landing'
            WHEN 'A50' THEN 'Route 50'
            WHEN 'AEH' THEN 'Egg Harbor Mainline Barrier'
            WHEN 'AH' THEN 'Hammonton Ramp'
            WHEN 'AWN' THEN 'Winslow Ramp'
            WHEN 'AWL' THEN 'Williamstown Ramp'
            WHEN 'ACK' THEN 'Cross Keys'
            WHEN 'OCL' THEN 'Ocean City-Longport Bridge'
            WHEN 'CIB' THEN 'Corsons Inlet Bridge'
            WHEN 'TIB' THEN 'Townsends Inlet Bridge'
            WHEN 'GSB' THEN 'Grassy Sound Bridge'
            WHEN 'MTB' THEN 'Middle Thorofare Bridge'
            -- DRPA
            WHEN 'BRB' THEN 'Betsy Ross Br'
            WHEN 'BFB' THEN 'Ben Franklin Br'
            WHEN 'WWB' THEN 'Walt Whitman Br'
            WHEN 'CBB' THEN 'Commodore Barry Br'
            -- DRBA
            WHEN 'DMB' THEN 'Delaware Memorial Br'
            -- BCBC
            WHEN 'TPB' THEN 'Tacony Palmyra Br'
            WHEN 'BBB' THEN 'Burlington Bristol Br'
            -- DRJTBC
            WHEN 'T-M' THEN 'Trenton-Morrisville Br'
            WHEN 'NHL' THEN 'New Hope-Lambertville Br'
            WHEN 'I78' THEN 'I-78 Br'
            WHEN 'E-P' THEN 'Easton-Phillipsburg Br'
            WHEN 'P-C' THEN 'Portland-Columbia Br'
            WHEN 'DWG' THEN 'Delaware Water Gap Br'
            WHEN 'M-M' THEN 'Milford-Montague Br'
            WHEN 'O78' THEN 'Interstate 78-ORT'
            WHEN 'ODW' THEN 'Delaware Water Gap-ORT'
            WHEN 'OSF' THEN 'Scudder Falls Br'
            ELSE NULL  -- Unknown values become NULL
        END as exit_plaza_name
        
    FROM cleaned
)

SELECT * FROM enriched